### ISSUE TITLE
Ability to subscribe by email

### ISSUE THREAD

**Issue by andrewm4894** [scalingpythonml/scalingpythonml.github.io#3]
Hello! I was looking for somewhere on the blog to subscribe by email as I dont really use any rss readers anymore since google reader was killed :(

Anyway - I like to actually subscribe via my email sometimes to interesting blogs like this as it can increase the probability I might find something interesting and easier sometimes to just manage my email as opposed to yet another rss reader app. 

So just wanted to see if I either missed some sort of box somewhere to subscribe to get new posts by email or if this might be something you are thinking about adding or not. 

Cheers, love all the stuff you doing!

**Comment by holdenk** [comment]
Thank you! I've got a page up http://scalingpythonml.com/mailinglist.html I'll figure out how to add it to the header tonight :)

**Comment by holdenk** [comment]
And I've added it to the header :) Thank's @andrewm4894 for the suggestion :)
